### ISSUE TITLE
Basic template examples should be included

### ISSUE THREAD

**Issue by mgrundkoetter** [siwaonline/social_stream#4]
All the template folders are missing in the published version of the extension. Configured in the setup.txt are the paths:

```
plugin.tx_news {
    view {
        templateRootPaths.9 = EXT:social_stream/Resources/Private/Templates/
        partialRootPaths.9 = EXT:social_stream/Resources/Private/Partials/
        layoutRootPaths.9 = EXT:social_stream/Resources/Private/Layouts/
    }
}
```

but none of those folders exist.

**Comment by siwa-pparzer** [comment]
This TypoScript is from an old version, where social_stream handled Templating itself.
Removed.
