### ISSUE TITLE
Usage of realurl without domain records

### ISSUE THREAD

**Issue by mgrundkoetter** [siwaonline/social_stream#5]
Using `realurl` does not necessarily mean the website also uses domain records. In the `BaseUtility.php` there is this code:

```php
if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('realurl')) {
  $rootline = \TYPO3\CMS\Backend\Utility\BackendUtility::BEgetRootLine($id);
  $host = \TYPO3\CMS\Backend\Utility\BackendUtility::firstDomainRecord($rootline);
  $_SERVER['HTTP_HOST'] = $host;
}
```
which will lead to problems later on (empty host).

Also the code
```php
$actualUrl = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
```
in the file `Classes/Controller/Wizard/TokenController.php` should be replaced by
```php
$actualUrl = $base . $_SERVER['REQUEST_URI'];
```
to avoid problems.

**Comment by siwa-pparzer** [comment]
solved by commit d997a82
