### ISSUE TITLE
Publication workflow

### ISSUE THREAD

**Issue by mgrundkoetter** [siwaonline/social_stream#7]
The latest versions 2.0.3 and 2.0.4 were not published to [TER](https://extensions.typo3.org/extension/social_stream/). It would be nice if you could tag (git) your released versions here, so using it with explicit link to the repository will be possible. Right now, there is no easy way to get the most recent version with composer :-(
BTW: there is also a quite easy way to automatically publish new versions to packagist by just registering it there and adding the hook here at GitHub, see https://packagist.org/packages/submit for details, takes just 10 minutes ;-)

**Comment by siwa-pparzer** [comment]
https://packagist.org/packages/siwaonline/social_stream
